//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public enum D3D11_COMPARISON_FUNC {
  NEVER = 1,
  LESS = 2,
  EQUAL = 3,
  LESS_EQUAL = 4,
  GREATER = 5,
  NOT_EQUAL = 6,
  GREATER_EQUAL = 7,
  ALWAYS = 8
}

}
