//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public class EffekseerBackendCore : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EffekseerBackendCore(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EffekseerBackendCore obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(EffekseerBackendCore obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~EffekseerBackendCore() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EffekseerCorePINVOKE.delete_EffekseerBackendCore(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public EffekseerBackendCore() : this(EffekseerCorePINVOKE.new_EffekseerBackendCore(), true) {
  }

  public static EffekseerCoreDeviceType GetDevice() {
    EffekseerCoreDeviceType ret = (EffekseerCoreDeviceType)EffekseerCorePINVOKE.EffekseerBackendCore_GetDevice();
    return ret;
  }

  public static bool InitializeWithOpenGL() {
    bool ret = EffekseerCorePINVOKE.EffekseerBackendCore_InitializeWithOpenGL();
    return ret;
  }

  public static bool InitializeWithDirectX9(global::System.IntPtr device) {
    bool ret = EffekseerCorePINVOKE.EffekseerBackendCore_InitializeWithDirectX9(device);
    return ret;
  }

  public static bool InitializeWithDirectX11(global::System.IntPtr device, global::System.IntPtr context) {
    bool ret = EffekseerCorePINVOKE.EffekseerBackendCore_InitializeWithDirectX11(device, context);
    return ret;
  }

  public static void Terminate() {
    EffekseerCorePINVOKE.EffekseerBackendCore_Terminate();
  }

}

}
